#!/usr/bin/env bash
name=$1
src=git@github.com:bryanhann/$name
dst=${BCH_BASE}/$name
[   -e $dst ] && echo " local $name exists"
[ ! -e $dst ] && echo " local $name cloning"
[ ! -e $dst ] &&           git clone ${src} ${dst}

