#!/usr/bin/env bash
[ "${BCH_BASE}" == "" ] && echo BCH_BASE not set && exit

install_one () {
    dst=${BCH_BASE}/${1}
    target1=${dst}/install.sh
    target2=${dst}/.bch/install.sh

    [ -f $target1 ] && echo }}} yes $target1
    [ -f $target1 ] || echo }}} no $target1
    [ -f $target1 ] && $target1
    [ -f $target2 ] && echo }} $target2
    [ -f $target2 ] && $target2
}

install_all () {
    for name in $(bch.cfg.locals); do
        install_one $name
    done
}


case $1. in
    all.)
        install_all
        exit
        ;;
    one.)
        install_one $2 
        exit
        ;;
esac

cat <<EOF
usage:
    $(basename $0) one NAME
    $(basename $0) all
EOF

