#!/usr/bin/env bash

cache=$BH0_BUILD/repos.txt

update () {
    gh repo list --no-archived -L 1000 \
    --json name,owner --jq .[].name > $cache
}

[ $1. == --update. ] && update
[ ! -f $cache      ] && update

cat $cache
