#!/usr/bin/env bash
[ -f ~/DEBUG ] && echo "[:dbg:] ++[$BASH_SOURCE]"
source $(readlink ${BASH_SOURCE[0]}).old/activate.sh
[ -f ~/DEBUG ] && echo "[:dbg:] --[$BASH_SOURCE]"

#==END OF SCRIPT===================================
