#!/usr/bin/env bash
echo ---.profile begin sourcing -----------------------
source $(readlink ${BASH_SOURCE[0]}).d/init.sh
echo ---.profile end sourcing -------------------------
echo "to turn on debugging, try 'touch ~/DEBUG'"
bash
print_exit_warning
# Nothing below this is under version control.

